# Site settings
title: System-on-Chip Design & Verification
author:
  name: Aidan Malone
  email: G00423306@atu.ie
description: "FPGA VGA Driver Project."

# Build settings
remote_theme: jekyll/minima
